### ISSUE TITLE
Request: Remove graphql-server package from pypi

### ISSUE THREAD

**Issue by KingDarBoja** [twidi/py-graphql-server#1]
Hi @twidi 

I opened this issue in order to ask for the removal of this package on the Python Package Index (PyPI), which is actually published as `graphql-server`: https://pypi.org/project/graphql_server/

The reason is due to recent renaming of `graphql-server-core` package of graphql-python organization into `graphql-server`, which also includes several features compatible with other graphql-python packages, hence the renaming and bump to version 3.

However, I noticed while publishing that the name was already taken as you can check the GH Action deploy workflow at https://github.com/graphql-python/graphql-server.

I would like to know what do you think about it and if you accept, would help us to finish the deployment and avoid having to pick a longer name like `graphql-server-3`.

Thanks!

**Comment by twidi** [comment]
Hey

Sorry for having this name blocked for years, at the time I was really into graphql, it was the beginning, but you know, life....

I just deleted the project on pypi, good luck with your project!

**Comment by KingDarBoja** [comment]
Thank you for you quick response! Good luck too with your projects mate 🚀
